spring.application.name=coordinator

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

kms.region=us-east-2
kms.signing-algorithm=ECDSA_SHA_256
kms.enabled=true
kms.key-id=${KMS_KEY-ID}
