spring.application.name=coordinator

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

kms.region=us-east-2
kms.signing-algorithm=ECDSA_SHA_256
kms.enabled=true
kms.key-id=${KMS_KEY_ID}

hcs.enabled=false
hcs.network=testnet
hcs.account-Id=${HEDERA_ACCOUNT_ID}
hcs.private-Key=${HEDERA_PRIVATE_KEY}
hcs.public-key-topic-id=${HEDERA_PUBLIC_KEY_TOPIC_ID}
hcs.decision-topic-id=${HEDERA_DECISION_TOPIC_ID}
hcs.surge-topic-id=${HEDERA_SURGE_TOPIC_ID}