spring.application.name=device
server.port=8081
device.simulation.id=device-01
device.simulation.name=Device Alpha
device.simulation.voltage.base=220.0
device.simulation.voltage.variation=4.0
device.simulation.schedule.ms=1000

device.simulation.surge.enabled=false
device.simulation.surgeVariation=80.0
device.simulation.surge.duration-ms=15000
device.simulation.surge.interval-ms=30000

device.network.host=localhost
coordinator.url=http://localhost:8080