package com.gridauthority.coordinator.domain.model;

public enum DeviceCommand {
    KEEP_RUNNING,
    SHUTDOWN,
    RESTART,
    OBSERVE, WARN, PREPARE_BACKUP, START_GENERATOR, SWITCH_TO_GENERATOR,
    SWITCH_TO_UPS, REDUCE_LOAD, SHED_NON_CRITICAL_LOAD, LOAD_SHED,
    TRANSFER_PRIORITY_LOAD, EMERGENCY_PROTECTION, RESTORE_GRID
}
